# Generated by Django 4.2.6 on 2023-11-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="r_freq",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="r_period",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateField(),
        ),
    ]
