# Generated by Django 4.2.6 on 2023-11-14 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_transaction_r_freq_transaction_r_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="r_freq",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="r_period",
        ),
    ]
