# Generated by Django 4.2.6 on 2023-11-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0002_rename_date_of_credit_friend_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friend",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="friend",
            name="debt",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10
            ),
        ),
    ]
