# Generated by Django 4.2.6 on 2023-11-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friends", "0007_remove_group_member_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="paid",
            field=models.CharField(
                choices=[("YES", "YES"), ("NO", "NO")], default="NO", max_length=3
            ),
        ),
    ]
