# Generated by Django 4.2.6 on 2023-11-22 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("friends", "0009_pairexpenses_alter_friend_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense_group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="pairexpenses",
            name="group_name",
        ),
        migrations.CreateModel(
            name="Expense_group_members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="friends.expense_group",
                    ),
                ),
                (
                    "member1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pairexpenses",
            name="member1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="friends.expense_group_members",
            ),
        ),
    ]
