# Generated by Django 4.2.6 on 2023-11-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expensegroups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="graph",
        ),
        migrations.AddField(
            model_name="edge",
            name="group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expensegroups.expensegroup",
            ),
        ),
        migrations.AlterField(
            model_name="expensegroup",
            name="name",
            field=models.CharField(default="GroupX", max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name="ExpenseGraph",
        ),
    ]
